# Site settings
title: DWM
email: tom@digitalwebmedia.co.uk
permalink: /:title
description: > # this means to ignore newlines until "baseurl:"
  Testing typography and deployment solutions for the new Digital Web Media website.
# url: "http://dwm.dev/" # Local
url: "http://tomhazledine.github.io/DWM_dev/" # the base hostname & protocol for your site
baseurl: "/DWM_dev/" # the subpath of your site, e.g. /blog/
twitter_username: jekyllrb
github_username:  tomhazledine


# Build settings
markdown: kramdown
kramdown:
  auto_ids: false
exclude: [config.rb,
          gulpfile.js,
          uncompressed,
          package.json,
          node_modules]
navigation:
  - text: Home
    url: 
  #- text: About
  #  url: about/
  - text: Work
    url: work/
  - text: Contact
    url: contact/
  #- text: Our Team
  #  url: team/

# Content settings
dwmEmail: hello@wearedwm.com
dwmTel: "01637 818271"
dwmTelLink: "01637818271"
dwmAddress:
  - addressLine: "DWM"
  - addressLine: "Victoria Parade Buildings"
  - addressLine: "East Street"
  - addressLine: "Newquay"
  - addressLine: "TR7 1BG"

# Social Links
twitter: "https://twitter.com/DigitalWebSW"
facebook: "https://www.facebook.com/digitalwebmediasw"
linkedin: "http://www.linkedin.com/company/digital-web-media"
google: "https://plus.google.com/116804388365827001557"